# Generated by Django 4.2.4 on 2023-08-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_lab', '0002_publishing_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishing_house',
            old_name='relation',
            new_name='book',
        ),
    ]
