# Generated by Django 4.2.4 on 2023-08-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_lab', '0003_rename_relation_publishing_house_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishing_house',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='publishing_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='book_lab.publishing_house'),
        ),
    ]
