# Generated by Django 4.2.4 on 2023-08-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_lab', '0005_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_lab/static/images/%y/%m/%d'),
        ),
    ]
